# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52718cbe34a72243aa3146f2dc507fcfc15b82e1c929806a067746af5efcb6a6d721dd25f7731e0f0e51bed37bc935e15f20794029ca225f5d58739ac52cf1b2

test:
  secret_key_base: 3920c60e558a8749ea406ed7b7e8a902dd1e036d305fb4bb96d990cdb007210318b0ceae756b7bce279e91ae58e0a0d4862a993815a04e028571070410c3aca0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
